= My Project
firstname lastname
1.0.0, {docdate}: Some notes
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// https://fontawesome.com/v4.7.0/icons/
icon:file-text-o[link=https://raw.githubusercontent.com/htl-leonding-college/asciidoctor-docker-template/master/asciidocs/{docname}.adoc] ‏ ‏ ‎
icon:github-square[link=https://github.com/htl-leonding-college/asciidoctor-docker-template] ‏ ‏ ‎
icon:home[link=https://htl-leonding.github.io/]
endif::backend-html5[]

// print the toc here (not at the default position)
//toc::[]

== Pflichtenheft "Was mache ich"

=== Ausgangssituation

In der heutigen Gesellschaft werden Plattformen für den Austausch und Verkauf von Dienstleistungen und Produkten immer häufiger genutzt, wie z. B. Willhaben oder Vinted.

=== Istzustand

Viele Menschen stehen regelmäßig vor den Herausforderungen, wie z. B. Rasenmähen, Einkaufen oder Schneeschaufeln.
Sie können diese Aufgaben nicht mehr verrichten aufgrund gesundheitlicher Einschränkungen, Zeitmangel oder der fehlenden Unterstützung im sozialen Umfeld.

=== Problemstellung

Die Beauftragung von professionellen Dienstleistern für kleine Alltagsaufgaben ist oft viel zu teuer oder mit großem organisatorischem Aufwand verbunden.
Zudem ist es vielen Menschen nicht möglich mit möglichen Helfern in Kontakt zu treten.

=== Aufgabenstellung

==== Funktionale Anforderungen

* Registrierung und Login
* Erstellung von Aufgaben
* Chat-Funktion zwischen hilfesuchendem Nutzer und helfendem Nutzer
* Aufträge annehmen und ablehnen
* Bewertungen an hilfesuchendem Nutzer und helfendem Nutzer

==== Nichtfunktionale Anforderungen (NFA)

* Schönes logisches Styling - benutzerfreundliches Design
* Verschlüsselung sensibler Daten wie Passwörter und den Zahlungsinformationen
* Die Plattform muss auch bei vielen Nutzern einwandfrei laufen



=== Ziele


* Menschen sollen einfache, schnelle Hilfe bekommen.
* Es soll die lokale Zusammenarbeit und die Gemeinschaft gefördert werden.
* Helfende Nutzer verdienen ein zusätzliches Einkommen.


=== Mengengerüst
----
?
----
=== Rahmenbedingungen

* Java und JavaFX
* komplett Client seitige Programmierung - kein Server
* IDE: IntelliJ IDEA


