name: java-test

on:
#   push:
#     branches:
#       - feat/**
#       - task/**
#       - hotfix/**
#     paths:
#       - javafx/**
  pull_request:
    branches:
      - dev
      - main
      - feat/**
    types: [opened, synchronize, reopened]
    paths:
      - javafx/**
  workflow_dispatch:

jobs:
  test:
    name: Run Java Tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Docker Compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./javafx/src/main/docker/docker-compose.yaml"
          services: |
            postgres

      - name: Setup Java Temurin 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Test Java
        run: |
          cd javafx &&
          mvn --batch-mode --update-snapshots clean verify

      - name: Report CheckStyle Results
        if: always()
        uses: motlin/checkstyle-results@v1
        with:
          checkstyle_files: "**/checkstyle-result.xml"
